/**
 * Local embedding provider for Graphweft's opt-in semantic search.
 *
 * Privacy contract: embeddings are generated by a server the USER runs on their own machine
 * (Ollama, LM Studio, llama.cpp — anything exposing Ollama's /api/embed). The endpoint is
 * strictly validated to be loopback-only, so enabling this feature never sends code off the
 * machine. No model weights ship in the extension; no new npm dependencies (global fetch).
 *
 * vscode-free so the validation and request shaping are unit-testable.
 */

export interface EmbeddingProviderConfig {
  /** Base URL of the local server, e.g. http://localhost:11434 */
  endpoint: string;
  /** Embedding model name the server should use, e.g. nomic-embed-text */
  model: string;
}

export interface EmbeddingProvider {
  /** Identity of the backend (endpoint + model), used to invalidate stored vectors. */
  id: string;
  /** True when the server is reachable and answering. */
  isAvailable(): Promise<boolean>;
  /** Embed a batch of texts; returns one vector per input, in order. Throws on failure. */
  embed(texts: string[]): Promise<number[][]>;
}

const LOOPBACK_HOSTS = new Set(['localhost', '127.0.0.1', '[::1]', '::1', '0.0.0.0']);

/**
 * Returns the parsed URL when the endpoint is a well-formed loopback HTTP(S) URL,
 * otherwise undefined. This is the privacy gate: anything non-local is rejected.
 */
export function validateLocalEndpoint(endpoint: string): URL | undefined {
  let url: URL;
  try {
    url = new URL(endpoint);
  } catch {
    return undefined;
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return undefined;
  return LOOPBACK_HOSTS.has(url.hostname.toLowerCase()) ? url : undefined;
}

interface OllamaEmbedResponse {
  embeddings?: number[][];
  /** Older Ollama versions answer /api/embeddings (singular input) with `embedding`. */
  embedding?: number[];
}

/** Embedding provider speaking Ollama's REST API against a validated loopback endpoint. */
export class OllamaEmbeddingProvider implements EmbeddingProvider {
  public readonly id: string;
  private readonly base: URL;
  private readonly model: string;

  /** Throws if the endpoint is not loopback — callers surface that as a config error. */
  public constructor(config: EmbeddingProviderConfig) {
    const url = validateLocalEndpoint(config.endpoint);
    if (!url) {
      throw new Error(
        `Semantic search endpoint must be a local (loopback) URL like http://localhost:11434 — got "${config.endpoint}". ` +
          'Graphweft never sends code to a remote embedding service.',
      );
    }
    this.base = url;
    this.model = config.model;
    this.id = `${url.origin}::${config.model}`;
  }

  public async isAvailable(): Promise<boolean> {
    try {
      const response = await fetch(new URL('/api/tags', this.base), { signal: AbortSignal.timeout(2000) });
      return response.ok;
    } catch {
      return false;
    }
  }

  public async embed(texts: string[]): Promise<number[][]> {
    if (texts.length === 0) return [];
    const response = await fetch(new URL('/api/embed', this.base), {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ model: this.model, input: texts }),
      signal: AbortSignal.timeout(120000),
    });
    if (!response.ok) {
      throw new Error(`Local embedding server answered ${response.status} ${response.statusText} for model "${this.model}".`);
    }
    const data = (await response.json()) as OllamaEmbedResponse;
    const embeddings = data.embeddings ?? (data.embedding ? [data.embedding] : undefined);
    if (!embeddings || embeddings.length !== texts.length) {
      throw new Error('Local embedding server returned an unexpected response shape.');
    }
    return embeddings;
  }
}
